
name: Build and Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  run_vps_scripts:
    name: remote ssh command
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git@github.com:Wasimba-Technologies/mymenu.git

